name: Terraform Pipeline

on:
  push:
    branches:
      - dev
    paths:
      - terraform/**

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Change to terraform directory
        run: cd terraform

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Validate Terraform configuration
        run: terraform -chdir=terraform validate

      - name: Plan Terraform changes
        run: terraform -chdir=terraform plan

      - name: Apply Terraform changes
        run: terraform -chdir=terraform apply -auto-approve
